AWSTemplateFormatVersion: 2010-09-09
Description: Base network setup

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

  VpcCidrBlock:
    Type: String 
    Description: CIDR block for the VPC
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  LogBucketArn:
    Description: Log bucket form SSM Parameter
    Type: AWS::SSM::Parameter::Value<String> 

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-vpc

  VpcIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String 
      Description: !Sub Stores ${Project}-${Stage}-${Component} Vpc ID
      Name: !Sub /${Project}/${Stage}/${Component}/vpc/vpc-id
      Tier: Standard
      Value: !Ref Vpc
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-vpc-id

  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      LogDestination: !Sub ${LogBucketArn}/vpc-flow-logs/vpc/
      LogDestinationType: s3
      ResourceId: !Ref Vpc
      ResourceType: VPC
      TrafficType: ALL        
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-flowlog

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-internet-gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-public-route-name

  PublicRouteTableIdParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project}-${Stage}-${Component} PublicRouteTableID
        Tier: Standard
        Name: !Sub /${Project}/${Stage}/${Component}/public-route-table/rt-id
        Value: !Ref PublicRouteTable
        Tags:
          Name: !Sub ${Project}-${Stage}-${Component}-public-route-table-id          


  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway    

Outputs:
  VpcId:
    Description: The ID of VPC
    Value: !Ref Vpc
  VpcIdParamName:
    Description: The name of SSM parameter where Id of VPC is stored
    Value: !Ref VpcIdParam
