AWSTemplateFormatVersion: 2010-09-09
Description: Simple website S3 bucket

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project information
        Parameters:
          - Project
          - Component 
      - Label:
          default: Deployment information
          Parameters:
            - Stage

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,20}$
  Stage:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,20}$

Resources: 
  S3Website:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      BucketName:  !Sub ${Project}-${Stage}-${Component}
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Website
      PolicyDocument: 
        Id: S3WebsitePolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Website
                - /*

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Website.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketName:
    Value: !Ref S3Website
    Description: Backet Name
      