AWSTemplateFormatVersion: 2010-09-09
Description: Bucket for artifacts

Parameters: 
  Project:  
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Versioning:
    Description: Is versioning enabled?
    Type: String 
    AllowedValues: 
      - 'true'
      - 'false'

Conditions: 
  IsVersioningEnabled: !Equals [!Ref Versioning, 'true' ]

Resources: 
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: !If
        - IsVersioningEnabled
        - Status: Enabled
        - !Ref AWS::NoValue   
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-artifact-bucket

  ArtifactBucketNameParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Value: !Ref ArtifactBucket
        Tier: Standard
        Name: !Sub /${Project}/${Stage}/${Component}/artifact-bucket/bucket-name
        Description: !Sub Stores ${Project} ${Stage} Artifcat bucket name
        Tags:
          Name: !Sub ${Project}-${Stage}-${Component}-artifact-bucket-name-param             

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
  ArtifactBucketNameParamName:
    Value: !Ref ArtifactBucketNameParam