AWSTemplateFormatVersion: 2010-09-09
Description: bucket with logs

Parameters: 
  Project:  
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources: 
  s3LogBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: LogDeliveryWrite
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-log-bucket

Outputs:
  LogBucketName:
    Value: !Ref s3LogBucket
