AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
Resources:
  LogBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/website-simple-dev-nested-artifact-artifactbucket-6gttesphkxb3/8ba712fc2cbab84b56ac5578e75f74bd.template
      Parameters:
        Project:
          Ref: Project
        Component:
          Ref: Component
        Stage:
          Ref: Stage
  Website:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/website-simple-dev-nested-artifact-artifactbucket-6gttesphkxb3/8027fb3ecb6fb40e466a8186bde5595a.template
      Parameters:
        Project:
          Ref: Project
        Component:
          Ref: Component
        Stage:
          Ref: Stage
        LogBucketName:
          Fn::GetAtt:
          - LogBucket
          - Outputs.LogBucketName
