AWSTemplateFormatVersion: 2010-09-09
Description: "Bucket creation"

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  BucketFunction:
    Description: Function of the bucket
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain    
    Properties:
      VersioningConfiguration:
        Status: Enabled 
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-${BucketFunction}-bucket
    
  S3BucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: !Sub Stores ${Project}-${Stage}-${Component}-${BucketFunction} S3 Bucket
      Name: !Sub /${Project}/${Stage}/${Component}/${BucketFunction}-bucket/name
      Tier: Standard
      Type: String
      Value: !Ref S3Bucket 
      Tags: 
        Name: !Sub ${Project}-${Stage}-${Component}-${BucketFunction}-param-name

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: S3 bucket name
  S3BucketNameParam:
    Value: !Ref S3BucketNameParam
    Description: The name of the SSM parameter where the Name of the  Bucket is stored
